#!/usr/bin/env python3
"""
TikTok認証セットアップ

ブラウザでTikTokにGoogle認証ログイン → Cookie保存
初回のみ手動操作が必要（CAPTCHAやreCAPTCHA）

使い方:
  python3 tiktok_auth.py           # ブラウザ起動→ログイン→Cookie保存
  python3 tiktok_auth.py --check   # Cookie有効性チェック
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

PROJECT_DIR = Path(__file__).parent.parent
COOKIE_FILE = PROJECT_DIR / "data" / ".tiktok_cookies.txt"
COOKIE_JSON = PROJECT_DIR / "data" / ".tiktok_cookies.json"
ENV_FILE = PROJECT_DIR / ".env"


def load_env():
    """Load .env file"""
    if ENV_FILE.exists():
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ.setdefault(key.strip(), value.strip())


def setup_auth_interactive():
    """ブラウザでTikTokにログイン → Cookie保存"""
    try:
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.chrome.service import Service
    except ImportError:
        print("pip3 install selenium を実行してください")
        sys.exit(1)

    print("=== TikTok認証セットアップ ===")
    print()
    print("Chromeを起動してTikTokのログインページを開きます。")
    print("Google認証でログインしてください。")
    print()

    options = Options()
    options.add_argument("--start-maximized")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option('useAutomationExtension', False)

    # Mac Chrome path
    chrome_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    if os.path.exists(chrome_path):
        options.binary_location = chrome_path

    try:
        driver = webdriver.Chrome(options=options)

        # bot検知回避
        driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
            "source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
        })

        driver.get("https://www.tiktok.com/login/phone-or-email/email")
        print("ブラウザが開きました。")
        print("→ 「Googleで続ける」をクリックしてログインしてください。")
        print("→ ログイン完了を自動検知します（最大5分待機）")
        print()

        # ログイン完了をポーリングで自動検知（sessionid cookieの出現を待つ）
        max_wait = 600  # 10分
        poll_interval = 3
        elapsed = 0
        logged_in = False

        while elapsed < max_wait:
            time.sleep(poll_interval)
            elapsed += poll_interval
            try:
                cookies = driver.get_cookies()
                for c in cookies:
                    if c["name"] == "sessionid" and c.get("value"):
                        logged_in = True
                        break
                # sessionidがなくてもホームにリダイレクトされたか確認
                if not logged_in and "tiktok.com/foryou" in driver.current_url:
                    logged_in = True
                if not logged_in and "tiktok.com/@" in driver.current_url:
                    logged_in = True
            except Exception:
                pass

            if logged_in:
                print(f"✅ ログイン検知！（{elapsed}秒経過）")
                time.sleep(3)  # Cookie安定待ち
                break

            if elapsed % 15 == 0:
                print(f"   待機中... {elapsed}秒経過（ブラウザでログインしてください）")

        if not logged_in:
            print("⏰ タイムアウト（5分）。ブラウザは開いたまま。")
            print("   ログイン後、再度このスクリプトを実行してください。")
            driver.quit()
            return False

        # Cookie保存（JSON形式）
        cookies = driver.get_cookies()
        COOKIE_JSON.parent.mkdir(parents=True, exist_ok=True)
        with open(COOKIE_JSON, 'w') as f:
            json.dump(cookies, f, indent=2)

        # Cookie保存（Netscape形式 — tiktok-uploader用）
        with open(COOKIE_FILE, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was auto-generated by tiktok_auth.py\n")
            for cookie in cookies:
                secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                expiry = str(int(cookie.get("expiry", 0)))
                domain = cookie.get("domain", "")
                if not domain.startswith("."):
                    domain = "." + domain
                path = cookie.get("path", "/")
                f.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{cookie['name']}\t{cookie['value']}\n")

        # セッションIDの確認
        session_id = None
        for cookie in cookies:
            if cookie["name"] == "sessionid":
                session_id = cookie["value"]
                break

        print()
        if session_id:
            print(f"✅ 認証成功！ SessionID取得済み")
            print(f"   Cookie保存: {COOKIE_FILE}")
            print(f"   Cookie(JSON): {COOKIE_JSON}")
            print(f"   有効期限: Cookieの期限まで自動投稿可能")
        else:
            print("⚠️ sessionidが見つかりませんが、他のCookieは保存済み")
            print("   投稿時にエラーが出る場合は再度ログインしてください")

        driver.quit()
        return True

    except Exception as e:
        print(f"❌ エラー: {e}")
        print()
        print("手動でcookieを設定する場合:")
        print(f"1. Chrome で https://www.tiktok.com にログイン")
        print(f"2. F12 → Application → Cookies → .tiktok.com")
        print(f"3. 全Cookieをコピーして {COOKIE_JSON} に保存")
        return False


def check_cookies():
    """Cookie有効性チェック"""
    print("=== Cookie有効性チェック ===")

    if not COOKIE_FILE.exists() and not COOKIE_JSON.exists():
        print("❌ Cookieファイルが存在しません")
        print(f"   実行: python3 {__file__} でセットアップしてください")
        return False

    if COOKIE_JSON.exists():
        with open(COOKIE_JSON) as f:
            cookies = json.load(f)

        session_cookie = None
        for c in cookies:
            if c["name"] == "sessionid":
                session_cookie = c
                break

        if session_cookie:
            expiry = session_cookie.get("expiry", 0)
            import datetime
            if expiry > 0:
                exp_date = datetime.datetime.fromtimestamp(expiry)
                now = datetime.datetime.now()
                remaining = (exp_date - now).days
                print(f"✅ SessionID: あり")
                print(f"   有効期限: {exp_date.strftime('%Y-%m-%d %H:%M')}")
                print(f"   残り: {remaining}日")
                if remaining < 3:
                    print("   ⚠️ 期限切れ間近！再ログインを推奨")
                return remaining > 0
            else:
                print("✅ SessionID: あり（期限情報なし）")
                return True
        else:
            print("⚠️ SessionIDなし（他のCookieはあり）")
            print("   投稿時にエラーが出る可能性があります")
            return False

    if COOKIE_FILE.exists():
        with open(COOKIE_FILE) as f:
            content = f.read()
        has_session = "sessionid" in content
        print(f"Cookie(Netscape): {'✅ sessionidあり' if has_session else '⚠️ sessionidなし'}")
        return has_session

    return False


def main():
    load_env()

    parser = argparse.ArgumentParser(description="TikTok認証セットアップ")
    parser.add_argument("--check", action="store_true",
                        help="Cookie有効性チェック")
    args = parser.parse_args()

    if args.check:
        check_cookies()
    else:
        setup_auth_interactive()


if __name__ == "__main__":
    main()
